---
- name: Install and configure aptitude.
  when: ansible_os_family == "Debian"
  block:
    - name: Install aptitude.
      ansible.builtin.package:
        name: aptitude
        state: present
      become: true

    - name: Create the configuration directory.
      ansible.builtin.file:
        path: "{{ aptitude_configuration_directory }}"
        state: directory

    - name: Configure aptitude.
      ansible.builtin.copy:
        src: aptitude.config
        dest: "{{ aptitude_configuration_file }}"
