---
- name: Install Prometheus.
  ansible.builtin.package:
    name: golang-github-prometheus
    state: present
  become: true

- name: Configure the Prometheus environment.
  ansible.builtin.template:
    src: prometheus.j2
    dest: "{{ prometheus_environment_path }}"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - Restart Prometheus.

- name: Configure Prometheus.
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "/etc/prometheus/prometheus.yml"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - Reload Prometheus.
