---
- name: Install Screen.
  ansible.builtin.package:
    name: screen
    state: present
  become: "{{ False if ansible_system == 'Darwin' else True }}"

- name: Configure Screen.
  ansible.builtin.copy:
    src: .screenrc
    dest: "{{ ansible_user_dir }}/.screenrc"
    mode: '0644'
    owner: "{{ ansible_user_id }}"
    group: "{{ primary_user_group }}"
